### ISSUE TITLE
wrong key in load_reference_data when imported from yaml

### ISSUE THREAD

**Issue by 465b** [465b/nemf#75]
```
ref_data_path = self.configuration['fit_data_path']
```
should be
```
ref_data_path = self.configuration['ref_data_path']
```
Error:
```
Traceback (most recent call last):
  File "C:\Users\u241279\Documents\phd\crazy_model\dist\test_1_nemf.py", line 2, in <module>
    model = nemf.model_class('configuration_files/model_ms_16062020.yml')
  File "C:\Users\u241279\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nemf\models.py", line 28, in __init__
    ref_data, ref_headers = self.load_reference_data(fit_data_path)
  File "C:\Users\u241279\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nemf\models.py", line 74, in load_reference_data
    ref_data_path = self.configuration['fit_data_path']
KeyError: 'fit_data_path'
```

**Comment by 465b** [comment]
fixed

**Comment by 465b** [comment]
fixed
